<?php

namespace LoadingSplitBundle\Repository;

/**
 * BDPostgresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BDPostgresRepository extends \Doctrine\ORM\EntityRepository
{
}
