<?php

namespace LoadingSplitBundle\Repository;

/**
 * LoadingPoSkuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoadingPoSkuRepository extends \Doctrine\ORM\EntityRepository
{
}
