<?php

namespace LoadingSplitBundle\Repository;

/**
 * LoadingposkudetailfndRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoadingposkudetailfndRepository extends \Doctrine\ORM\EntityRepository
{
}
