<?php

namespace LoadingSplitBundle\Repository;

/**
 * LoadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoadingRepository extends \Doctrine\ORM\EntityRepository
{
}
