<?php

namespace LoadingSplitBundle\Repository;

/**
 * Loading_po_skuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Loading_po_skuRepository extends \Doctrine\ORM\EntityRepository
{
}
