<?php

namespace LoadingSplitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LoadingsplitskuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoadingsplitskuRepository extends \Doctrine\ORM\EntityRepository
{
	
}
