<?php

namespace LoadingSplitBundle\Repository;

/**
 * LoadingposkudetailfndRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoadingposkudetailfndRepository extends \Doctrine\ORM\EntityRepository
{
	public function findEntrepotByIdLoadingPoSku($idLoadingPoSku)
		{
		  $qb = $this->createQueryBuilder('a');

		  $qb->where('a.idloadingposku = :idLoadingPoSku')
			   ->setParameter('idLoadingPoSku', $idLoadingPoSku)
			 ->orderBy('a.entrepot', 'DESC')
		  ;
		  return $qb
			->getQuery()
			->getResult()
		  ;
		}
			
	public function findQuantitesByCpEntrepotIdLoadingPoSku($entrepot, $idLoadingPoSku)
		{	   
		  $query = $this->_em->createQuery(
		  'SELECT a FROM LoadingSplitBundle:Loadingposkudetailfnd a WHERE a.idloadingposku = :idloadingposku AND a.entrepot = :entrepot');
		  $query->setParameter('idloadingposku', $idLoadingPoSku);
		  $query->setParameter('entrepot', $entrepot);
		  
		  return $query ->getOneOrNullResult();
		}  
}
