<?php

namespace LoadingSplitBundle\Repository;

/**
 * PoDetailFndRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OldPoDetailFndRepository extends \Doctrine\ORM\EntityRepository
{
		public function findQuantitiesOrderedByPoEntrepotMad($po, $entrepot, $mad)
		{	   
		  $query = $this->_em->createQuery(
		  'SELECT a FROM LoadingSplitBundle:PoDetailFnd a WHERE a.numPo = :numPo AND a.entrepot = :entrepot AND a.dateMadRt = :mad');
		  $query->setParameter('numPo', $po);
		  $query->setParameter('entrepot', $entrepot);
		  $query->setParameter('mad', $mad);
		  return $query ->getOneOrNullResult();
		}  
}

class PoDetailFndRepository extends \Doctrine\ORM\EntityRepository
{
		public function findQuantitiesOrderedByPoEntrepotMad($po, $entrepot, $mad)
		{	   
		  $query = $this->_em->createQuery(
		  'SELECT a FROM LoadingSplitBundle:PoDetailFnd a WHERE a.numPo = :numPo AND a.entrepot = :entrepot');
		  $query->setParameter('numPo', $po);
		  $query->setParameter('entrepot', $entrepot);
		  return $query ->getOneOrNullResult();
		}  
}