<?php

namespace LoadingSplitBundle\Repository;

/**
 * QuantiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function findQuantitesByCpEntrepotIdLoadingPoSku($num_po, $ref, $entrepot, $idLoadingPoSku)
		{	   
		  $query = $this->_em->createQuery(
		  'SELECT a.quantites FROM LoadingSplitBundle:Quantite a WHERE a.num_po= :num_po a.ref = :ref AND a.idloadingposku = :idloadingposku AND a.entrepot = :entrepot');
		  $query->setParameter('num_po', $num_po);
		  $query->setParameter('ref', $ref);
		  $query->setParameter('idloadingposku', $idLoadingPoSku);
		  $query->setParameter('entrepot', $entrepot);
		  
		  return $query ->getOneOrNullResult();
		}
}
